name: spark_utils

channels:
  - esri
  - conda-forge

dependencies:
  - black>=21
  - jupyterlab
  - jupyterlab_code_formatter
  - pandoc
  - pip
  - pytest
  - python=3.9.*
  - pyarrow
  - pyspark=3.4.1
  - pyyaml
  - pip:
    - autodocsumm
    - build
    - bump2version
    - furo
    - nbsphinx
    - sphinx
    - sphinxcontrib-youtube
    - sphinx-autodoc-typehints
    - sphinx-copybutton
    - twine
